### PR TITLE
Fix URL normalization

### PR DESCRIPTION
**Pull request by ocubom**
URL normalization does not work when is set in options but not in HTML header.

This changes applies the normalization in both cases.

### CODE REVIEW

**Comment by dankantor** [comment]
Mine is breaking without this fix. Please merge!

**Comment by dankantor** [comment]
Actually, this fix removes a / when options.url is provided. Looks like this:

```
Sitemap: http:/example.comsitemap.xml
```

**Comment by haydenbleasel** [comment]
@ocubom can you sort out @dankantor's comment then I'll merge in?

**Comment by dankantor** [comment]
@haydenbleasel I pulled out options.url and put in a canonical tag just to try it, and got the same single / bug. It looks like the problem is with `path.join(url, '/')`

**Comment by haydenbleasel** [comment]
Yeah so it turns out, the [natural response](https://nodejs.org/api/path.html#path_path_join_path1_path2) is to strip the trailing slash. So `path.normalize(url) + '/'` is probably a suitable replacement.

**Comment by dankantor** [comment]
`path.normalize(url)` will still convert the double slash in `http://example.com` to `http:/example.com`

**Comment by haydenbleasel** [comment]
Okay fair enough. I think this needs to be handled upstream in robots-generator - we should just lazily pass a URL in and figure it out there.

**Comment by ocubom** [comment]
Perhaps we can use url module to solve this (just a quick test):

    url: options.url || url ? require('url').resolve(options.url || url, '/') : null

But moving this normalization step to robots-generator will be better

**Comment by haydenbleasel** [comment]
Hey all, `gulp-robots` 2.0.0 just released. Slightly new syntax but much easier to digest for you and me:

```
gulp.task('default', function () {
    gulp.src('index.html')
        .pipe(robots({
            useragent: '*',
            allow: ['folder1/', 'folder2/'],
            disallow: ['cgi-bin/']
        }))
        .pipe(gulp.dest('robots.txt'));
});
```

**Comment by dankantor** [comment]
👍

**Pull request closed without merging**
